[logger]
# Level of logging: 'error', 'warning', 'info', or 'debug'.
# Default: 'info'
level = "info"

[client]
# Controls whether the default sidebar page navigation in a multipage app is
# displayed.
# Default: true
showSidebarNavigation = false

[server]
# Max size, in megabytes, for files uploaded with the file_uploader.
# Default: 200
maxUploadSize = 200

[browser]
# Whether to send usage statistics to Streamlit.
# Default: true
gatherUsageStats = false

[theme]
# The preset Streamlit theme that your custom theme inherits from.
# One of "light" or "dark".
base ="dark"
